### ISSUE TITLE
env.manifest  Syntax Error

### ISSUE THREAD

**Issue by Luidog** [ahultgren/node-varium#3]
Varium is failing to parse any env.manifest file with more than one line. When attempting to do so the following error is returned:

`throw new SyntaxError(`Unexpected char ${char} in DeclarationType`);`

I tested this with the example given in the readme.

**Comment by ahultgren** [comment]
HI! Since i know it works for me and we use it in a lot of production servers I need more information. Is the actual unexpected char printed? What OS are you using?

**Comment by Luidog** [comment]
This error is :

throw new SyntaxError(`Unexpected ${char}`);

I am running OS 10.13.2

For further clarification, it seems to be from the new line character. If there is only one manifest definition it works, but once a second definition is added I get the error above.

I tried experimenting with the name of the manifest file. I have tried it name env.manifest and env.manifest.js, I get this error either way.

**Comment by ahultgren** [comment]
I was thinking it might have to do with the newline character too, but i'd expect windows to cause such issues. Would you like to post a gist with the exact contents of your manifest file?

About the error message what i mean is that it both prints the raw code of the error and the message itself (see screenshot below). But it looks like you paste the code, not the message.

![image](https://user-images.githubusercontent.com/1416726/34163390-df252586-e4d6-11e7-90de-389f02b3259b.png)

**Comment by Luidog** [comment]
Sorry, 

I was wondering why you asked for the message again. Here is the error:

SyntaxError: Unexpected
    at module.exports (/Documents/Development/fmqbo-3/node_modules/varium/src/interpret/lex.js:67:15)
    at module.exports.input (/Documents/Development/fmqbo-3/node_modules/varium/src/interpret/index.js:4:33)
    at R.curry (/Documents/Development/fmqbo-3/node_modules/varium/src/index.js:8:46)
    at /Documents/Development/fmqbo-3/node_modules/ramda/src/internal/_curryN.js:37:27
    at /Documents/Development/fmqbo-3/node_modules/ramda/src/internal/_arity.js:5:45
    at R.curry (/Documents/Development/fmqbo-3/node_modules/varium/src/index.js:49:10)
    at /Documents/Development/fmqbo-3/node_modules/ramda/src/internal/_curryN.js:37:27
    at /Documents/Development/fmqbo-3/node_modules/ramda/src/internal/_arity.js:6:49
    at R.curry (/Documents/Development/fmqbo-3/node_modules/varium/src/index.js:53:3)
    at /Documents/Development/fmqbo-3/node_modules/ramda/src/internal/_curryN.js:37:27

I will write up a gist.

**Comment by Luidog** [comment]
After some digging I found that it was an issue with my npm cache.
